version: "3"
services:

  # Runs the database for development
  db:
    image: postgres:15.1
    restart: on-failure
    volumes:
      # Move pgdata to subfolder to work around Docker bug: https://github.com/docker/for-linux/issues/380
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      # Redirect postgres port to 5433 locally so it doesn't conflict with an existing host postgres installation,
      # and that way we can always connect to the config from the host, even if the container gets a new IP assigned.
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: admin

  # Runs the database for testing
  db-test:
    image: postgres:15.1
    restart: on-failure
    ports:
      # Redirect postgres port to 5434 locally so it doesn't conflict with an existing host postgres installation,
      # and that way we can always connect to the config from the host, even if the container gets a new IP assigned.
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: admin
